#include "global.h"

HMODULE g_hModule = NULL;
uint64_t g_MyModuleBase = 0;
uint64_t g_MyModuleSize = 0;
uint64_t g_MyModuleEnd = 0;
DWORD   进程PID = 0;
DWORD   父进程PID = 0;
DWORD   g_MainThreadId = 0;
HANDLE g_hLoginMonitor = nullptr;
HANDLE g_hAfterLoginInit = nullptr;

HMODULE g_hWeixinDll = nullptr;
HMODULE g_hWeixinExe = nullptr;
HWND    g_WeixinMainHwnd = nullptr;
volatile uint64_t g_IsLogin = 0;
volatile uint64_t g_LoginProbeCalls = 0;
volatile uint64_t g_LoginProbeLast = 0;
volatile uint64_t g_LoginStateChanges = 0;
volatile uint64_t g_LoginStateLastChange = 0;
volatile uint64_t g_LoginStateSource = 0;
volatile uint64_t g_LoginProbeHookInstalled = 0;
volatile uint64_t g_LoginFinishCalls = 0;
volatile uint64_t g_LoginFinishContext = 0;
volatile uint64_t g_LoginFinishPayload = 0;
volatile uint64_t g_ProfileGetterCalls = 0;
volatile uint64_t g_ProfileGetterNullStreak = 0;
volatile uint64_t g_MessageReceiveCalls = 0;
volatile uint64_t g_MessageCallbackPosts = 0;
volatile uint64_t g_MessageHookInstalled = 0;
volatile uint64_t g_MsgReplaceHandlerCalls = 0;
volatile uint64_t g_MsgReplaceHandlerContext = 0;
volatile uint64_t g_MsgReplaceHandlerSync = 0;
volatile uint64_t g_PlainTextMsgHandlerCalls = 0;
volatile uint64_t g_PlainTextMsgHandlerContext = 0;
volatile uint64_t g_PlainTextMsgHandlerObject = 0;
volatile uint64_t g_MsgSourceParserCalls = 0;
volatile uint64_t g_MsgWordingParserCalls = 0;
volatile uint64_t g_MsgWordingObject = 0;
volatile uint64_t g_MessageStructCopyCalls = 0;
volatile uint64_t g_MessageStructSource = 0;
volatile uint64_t g_MessageStructTarget = 0;
char g_MessageStructTalker[256]{};
char g_MessageStructContent[4096]{};
char g_MessageStructExtra1[4096]{};
char g_MessageStructExtra2[4096]{};
volatile uint64_t g_RawSyncMsgProcessorCalls = 0;
volatile uint64_t g_RawSyncMsgItemCount = 0;
volatile uint64_t g_RawSyncMsgLastItem = 0;
volatile uint64_t g_RawSyncMsgLastType = 0;
volatile uint64_t g_SyncBatchProcessorCalls = 0;
volatile uint64_t g_SyncBatchItemCount = 0;
volatile uint64_t g_SyncBatchLastContext = 0;
volatile uint64_t g_SyncBatchLastVector = 0;
volatile uint64_t g_SyncBatchLastCandidate = 0;
volatile uint64_t g_SyncBatchVtableMatches = 0;
volatile uint64_t g_SyncBatchFieldReadCalls = 0;
volatile uint64_t g_SyncBatchLastMsgType = 0;
char g_SyncBatchText1[4096]{};
char g_SyncBatchText2[4096]{};
char g_SyncBatchText3[4096]{};
char g_SyncBatchText4[4096]{};
char g_SyncBatchFromUsername[4096]{};
char g_SyncBatchToUsername[4096]{};
char g_SyncBatchContent[4096]{};
volatile uint64_t g_RevokeDetectedCount = 0;
volatile uint64_t g_RevokePostedCount = 0;
volatile uint64_t g_RevokeLastNewMsgId = 0;
char g_RevokeLastFrom[4096]{};
char g_RevokeLastSender[4096]{};
char g_RevokeLastTip[4096]{};
char g_RevokeLastTalker[4096]{};
volatile uint64_t g_RevokeLastRevokeTime = 0;
volatile uint64_t g_RevokeDistinctCount = 0;
volatile uint64_t g_RevokeSuppressedCount = 0;
volatile LONG g_AntiRevokeEnabled = 0;
volatile LONG g_RevokeTipInjectEnabled = 0;
volatile uint64_t g_RevokeTipInjectCalls = 0;
volatile uint64_t g_RevokeTipInjectOk = 0;
volatile uint64_t g_RevokeTipInjectFail = 0;
volatile uint64_t g_RevokeConsumeOverrides = 0;
volatile uint64_t g_AutoReplyQueued = 0;
volatile uint64_t g_AutoReplySent = 0;
volatile uint64_t g_AutoReplyFailed = 0;
volatile uint64_t g_AutoReplyCandidates = 0;
volatile uint64_t g_AutoReplyFriendCandidates = 0;
volatile uint64_t g_AutoReplyGroupCandidates = 0;
volatile uint64_t g_AutoReplyGroupSkipped = 0;
volatile uint64_t g_AutoReplySelfSkipped = 0;
volatile uint64_t g_AutoReplyGroupEnabled = 0;
char g_AutoReplyLastChatType[16]{};
char g_AutoReplyLastSender[256]{};
char g_AutoReplyLastRoom[256]{};
volatile uint64_t g_SendRequestObserveCalls = 0;
volatile uint64_t g_SendRequestObserveVtableValid = 0;
volatile uint64_t g_SendRequestObserveFieldReadCalls = 0;
volatile uint64_t g_SendRequestObserveLastSource = 0;
volatile uint64_t g_SendRequestObserveLastDestination = 0;
volatile uint64_t g_SendRequestObserveLastVtable = 0;
volatile uint64_t g_SendRequestObserveLastField10Object = 0;
volatile uint64_t g_SendRequestObserveLastField20Object = 0;
volatile uint64_t g_SendRequestObserveHookInstalled = 0;
char g_SendRequestObserveField10[4096]{};
char g_SendRequestObserveField20[4096]{};
volatile uint64_t g_SendElementObserveCalls = 0;
volatile uint64_t g_SendElementObserveFlagMatches = 0;
volatile uint64_t g_SendElementObserveFieldReadCalls = 0;
volatile uint64_t g_SendElementObserveLastSource = 0;
volatile uint64_t g_SendElementObserveLastDestination = 0;
volatile uint64_t g_SendElementObserveLastFlags = 0;
volatile uint64_t g_SendElementObserveHookInstalled = 0;
volatile uint64_t g_SendElementObserveLastField1Object = 0;
volatile uint64_t g_SendElementObserveLastField1Wrapper = 0;
char g_SendElementObserveField1[4096]{};
char g_SendElementObserveField10[4096]{};
char g_SendElementObserveField20[4096]{};
volatile uint64_t g_SendContentObserveCalls = 0;
volatile uint64_t g_SendContentObserveLastArg1 = 0;
volatile uint64_t g_SendContentObserveLastArg2 = 0;
volatile uint64_t g_SendContentObserveLastObject = 0;
volatile uint64_t g_SendContentObserveLastVtable = 0;
volatile uint64_t g_SendContentObserveReceiverOffset = UINT64_MAX;
volatile uint64_t g_SendContentObserveContentOffset = UINT64_MAX;
volatile uint64_t g_SendContentObserveHookInstalled = 0;
char g_SendContentObserveReport[16384]{};
volatile uint64_t g_XmlProbeArmed = 0;
volatile uint64_t g_XmlProbeCaptured = 0;
volatile uint64_t g_XmlProbeSendCalls = 0;
volatile uint64_t g_XmlProbeVtableRva = 0;
volatile uint64_t g_XmlProbeXmlOffset = UINT64_MAX;
volatile uint64_t g_XmlProbeWxidOffset = UINT64_MAX;
char g_XmlProbeFieldMap[16384]{};
volatile uint64_t g_ForwardObserveCalls = 0;
volatile uint64_t g_ForwardObserveHookInstalled = 0;
volatile uint64_t g_AppMsgSubmitArmed = 0;
volatile uint64_t g_AppMsgSubmitCaptured = 0;
volatile uint64_t g_AppMsgSubmitCalls = 0;
volatile uint64_t g_AppMsgSubmitHookInstalled = 0;
volatile uint64_t g_AppMsgSubmitManager = 0;
volatile uint64_t g_TaskDispatchCalls = 0;
volatile uint64_t g_TaskDispatchHookInstalled = 0;
volatile uint64_t g_AppMsgTemplate = 0;
volatile uint64_t g_AppMsgSubmitRequestObj = 0;
volatile uint64_t g_AppMsgSubmitRequestVtable = 0;
volatile uint64_t g_AppMsgSubmitA3 = 0;
volatile uint64_t g_AppMsgSubmitA4 = 0;
volatile uint64_t g_AppMsgSubmitA5 = 0;
char g_AppMsgSubmitReport[65536]{};
volatile uint64_t g_AppMsgSendCalls = 0;
volatile uint64_t g_AppMsgDispatchOk = 0;
volatile uint64_t g_AppMsgDispatchFail = 0;
volatile uint64_t g_AppMsgSerializeCalls = 0;
volatile uint64_t g_AppMsgResponseCalls = 0;
volatile uint64_t g_AppMsgLastRespSize = 0;
volatile int64_t  g_AppMsgLastRet = 0;
volatile uint64_t g_SysMsgParserCalls = 0;
volatile uint64_t g_HistoryAddMsgCalls = 0;
volatile uint64_t g_HistoryAddMsgCommitCalls = 0;
volatile uint64_t g_SqlitePrepareCalls = 0;
volatile uint64_t g_SqlitePrepareV2Calls = 0;
volatile uint64_t g_SqliteBindTextCalls = 0;
volatile uint64_t g_SqliteBindText16Calls = 0;
volatile uint64_t g_SqliteStepCalls = 0;
volatile uint64_t g_SqliteHookInstalled = 0;
volatile uint64_t g_SqliteApiTable = 0;
volatile uint64_t g_SqlitePrepareTarget = 0;
volatile uint64_t g_SqlitePrepareV2Target = 0;
volatile uint64_t g_SqliteBindTextTarget = 0;
volatile uint64_t g_SqliteBindText16Target = 0;
volatile uint64_t g_SqliteStepTarget = 0;
volatile uint64_t g_SqliteLastDbHandle = 0;
volatile uint64_t g_SqliteLastDbThreadId = 0;
volatile uint64_t g_SqliteContactDbHandle = 0;
volatile uint64_t g_SqliteContactDbThreadId = 0;
char g_SqliteLastDbPath[512]{};
char g_SqliteContactDbPath[512]{};
volatile uint64_t g_ContactQueryRequests = 0;
volatile uint64_t g_ContactQueryTryCalls = 0;
volatile uint64_t g_ContactQueryClaims = 0;
volatile uint64_t g_ContactQueryExecuteCalls = 0;
volatile uint64_t g_ContactQueryCompleteCalls = 0;
volatile uint64_t g_ContactQueryLastDb = 0;
volatile uint64_t g_ContactParserCalls = 0;
volatile uint64_t g_ContactParserRows = 0;
volatile uint64_t g_ContactParserHookInstalled = 0;
volatile uint64_t g_ContactParserLastRecord = 0;
char g_ContactParserLastUsername[256]{};
char g_ContactParserLastAlias[256]{};
char g_ContactParserLastNickname[512]{};
char g_ContactParserLastBigHeadUrl[1024]{};
char g_ContactParserLastSmallHeadUrl[1024]{};
volatile uint64_t g_ContactDetailCalls = 0;
volatile uint64_t g_ContactDetailHookInstalled = 0;
volatile uint64_t g_ContactDetailLastManager = 0;
volatile uint64_t g_ContactDetailLastOutput = 0;
volatile uint64_t g_ContactDetailLastRequest = 0;
volatile uint64_t g_ContactDetailLastStatus = 0;
volatile uint64_t g_ContactDetailLastResult = 0;
volatile uint64_t g_ContactDetailRecordCalls = 0;
volatile uint64_t g_ContactDetailLastRecord = 0;
char g_ContactDetailLastUsername[256]{};
char g_ContactDetailLastAlias[256]{};
char g_ContactDetailLastNickname[512]{};
volatile uint64_t g_ContactStartupCalls = 0;
volatile uint64_t g_ContactStartupRecords = 0;
volatile uint64_t g_ContactStartupHookInstalled = 0;
volatile uint64_t g_ContactStartupLastVector = 0;
volatile uint64_t g_ContactStartupLastCount = 0;
char g_ContactStartupLastUsername[256]{};
char g_ContactStartupLastAlias[256]{};
char g_ContactStartupLastNickname[512]{};
volatile uint64_t g_ContactListSourceCalls = 0;
volatile uint64_t g_ContactListSourceRecords = 0;
volatile uint64_t g_ContactListSourceHookInstalled = 0;
volatile uint64_t g_ContactListSourceLastVector = 0;
volatile uint64_t g_ContactListSourceLastCount = 0;
char g_ContactListSourceLastUsername[256]{};
char g_ContactListSourceLastAlias[256]{};
char g_ContactListSourceLastNickname[512]{};
volatile uint64_t g_ContactResponseBatchCalls = 0;
volatile uint64_t g_ContactResponseBatchRecords = 0;
volatile uint64_t g_ContactResponseBatchHookInstalled = 0;
volatile uint64_t g_ContactResponseBatchLastVector = 0;
volatile uint64_t g_ContactResponseBatchLastCount = 0;
volatile uint64_t g_ContactResponseSplitCalls = 0;
volatile uint64_t g_ContactResponseSplitRecords = 0;
volatile uint64_t g_ContactResponseSplitHookInstalled = 0;
volatile uint64_t g_ContactResponseSplitLastInputCount = 0;
volatile uint64_t g_ContactResponseSplitLastOutputCount = 0;
volatile uint64_t g_ContactPipelineCalls = 0;
volatile uint64_t g_ContactPipelineRecords = 0;
volatile uint64_t g_ContactPipelineHookInstalled = 0;
volatile uint64_t g_ContactPipelineLastCount = 0;
volatile uint64_t g_ContactRecordParserCalls = 0;
volatile uint64_t g_ContactRecordParserRows = 0;
volatile uint64_t g_ContactRecordParserHookInstalled = 0;
volatile uint64_t g_ContactManagerListCalls = 0;
volatile uint64_t g_ContactManagerListRecords = 0;
volatile uint64_t g_ContactManagerListHookInstalled = 0;
volatile uint64_t g_ContactManagerListLastCount = 0;
volatile uint64_t g_ContactManagerListLastVector = 0;
volatile uint64_t g_ContactManagerListLastBegin = 0;
volatile uint64_t g_ContactManagerListLastEnd = 0;
volatile uint64_t g_ContactManagerListLastSpan = 0;
volatile uint64_t g_ContactManagerListLastMode = 0;
volatile uint64_t g_ContactManagerListLastCaller = 0;
volatile uint64_t g_ContactManagerListMaxCount = 0;
char g_ContactManagerListLastUsername[256]{};
volatile uint64_t g_ContactSyncSourceCalls = 0;
volatile uint64_t g_ContactSyncSourceItems = 0;
volatile uint64_t g_ContactSyncSourceHookInstalled = 0;
volatile uint64_t g_ContactSyncSourceLastVector = 0;
volatile uint64_t g_ContactSyncSourceLastCount = 0;
char g_ContactSyncSourceFirstUsername[256]{};
char g_ContactSyncSourceLastUsername[256]{};
volatile uint64_t g_ContactSyncCallbackCalls = 0;
volatile uint64_t g_ContactSyncCallbackRecords = 0;
volatile uint64_t g_ContactSyncCallbackHookInstalled = 0;
volatile uint64_t g_ContactSyncCallbackLastCount = 0;
volatile uint64_t g_ContactSyncCallbackLastVector = 0;
char g_ContactSyncCallbackFirstUsername[256]{};
char g_ContactSyncCallbackLastUsername[256]{};
volatile uint64_t g_ContactListBuildCalls = 0;
volatile uint64_t g_ContactListBuildRecords = 0;
volatile uint64_t g_ContactListBuildHookInstalled = 0;
volatile uint64_t g_ContactListBuildLastCount = 0;
volatile uint64_t g_ContactListBuildLastVector = 0;
char g_ContactListBuildFirstUsername[256]{};
char g_ContactListBuildLastUsername[256]{};
volatile uint64_t g_ContactSessionInfoCalls = 0;
volatile uint64_t g_ContactSessionInfoItems = 0;
volatile uint64_t g_ContactSessionInfoHookInstalled = 0;
volatile uint64_t g_ContactSessionInfoLastCount = 0;
volatile uint64_t g_ContactSessionInfoLastVector = 0;
char g_ContactSessionInfoFirstUsername[256]{};
char g_ContactSessionInfoLastUsername[256]{};
volatile uint64_t g_ContactGeneralQueryCalls = 0;
volatile uint64_t g_ContactGeneralQueryRows = 0;
volatile uint64_t g_ContactGeneralQueryHookInstalled = 0;
volatile uint64_t g_ContactGeneralQueryLastRow = 0;
char g_ContactGeneralQueryLastField0[256]{};
char g_ContactGeneralQueryLastField1[256]{};
char g_ContactGeneralQueryLastField2[256]{};
char g_ContactGeneralQueryLastField3[256]{};
char g_ContactGeneralQueryLastField4[256]{};
char g_ContactGeneralQueryLastField5[256]{};
char g_ContactGeneralQueryLastField6[256]{};
char g_ContactGeneralQueryLastField7[256]{};
char g_SqliteLastSql[4096]{};
char g_SqliteInterestingSql[4096]{};
char g_SqliteLastBindText[4096]{};
char g_SqliteInterestingBindText[4096]{};
SqliteBindTrace g_SqliteBindTraces[kSqliteBindTraceCapacity]{};
volatile uint64_t g_SqliteBindTraceIndex = 0;
volatile uint64_t g_MessageParserCalls = 0;
volatile uint64_t g_MessageParserLastObject = 0;
volatile uint64_t g_SyncContextObject = 0;
volatile uint64_t g_FieldLookupCalls = 0;
volatile uint64_t g_FieldLookupLastKey = 0;
char g_FieldLookupLastKeyText[128]{};
volatile uint64_t g_FieldFromCalls = 0, g_FieldContentCalls = 0, g_FieldMsgCalls = 0, g_FieldWordingCalls = 0;
char g_FieldFromText[256]{}, g_FieldContentText[4096]{}, g_FieldMsgText[4096]{}, g_FieldWordingText[4096]{};
char g_FieldMsgOutputHex[256]{};
char g_FieldMsgNodeHex[512]{};
char g_FieldMsgValueHex[512]{};
char g_FieldWordingOutputHex[256]{};
char g_FieldWordingNodeHex[512]{};
char g_FieldWordingValueHex[512]{};
char g_DbDebugText[512]{};
FieldLookupTrace g_FieldLookupTraces[kFieldLookupTraceCapacity]{};
volatile uint64_t g_FieldLookupTraceIndex = 0;
MessageBranchTrace g_MessageBranchTraces[kMessageBranchTraceCapacity]{};
volatile uint64_t g_MessageBranchTraceIndex = 0;
volatile uint64_t g_ProfileObject = 0;
volatile uint64_t g_ProfileFieldCalls = 0;
volatile uint64_t g_ProfileFieldObject = 0;
volatile uint64_t g_ProfileFieldDescriptor = 0;
volatile uint64_t g_ProfileLookupCalls = 0;
char g_ProfileLookupLastKey[128]{};
char g_ProfileLookupLastValue[1024]{};
volatile uint64_t g_ProfileContainer830Calls = 0;
volatile uint64_t g_ProfileContainer830Object = 0;
volatile uint64_t g_ProfileContainer830Root = 0;
volatile uint64_t g_ProfileContainer830Second = 0;
volatile uint64_t g_ProfileContainerFC00Calls = 0;
volatile uint64_t g_ProfileContainerFC00Object = 0;
volatile uint64_t g_ProfileContainerFC00Root = 0;
volatile uint64_t g_ProfileContainerFC00Second = 0;
volatile uint64_t g_ManagerContainerGetterCalls = 0;
volatile uint64_t g_ManagerContainerObject = 0;
ProfileFieldTrace g_ProfileTraces[kProfileTraceCapacity]{};
volatile uint64_t g_ProfileTraceIndex = 0;
volatile uint64_t g_getprofile = 0;
CRITICAL_SECTION g_dbMgrCriticalSection;

volatile bool g_LoginMonitorRunning = true;
std::string g_CallBack_Url;

std::wstring g_AppDataDir;
std::wstring g_DocumentDir;
std::wstring g_UsersDir;

SelfInfo_t SelfInfo;

